spring.application.name=springai-embedding
spring.profiles.include=secret

## 서버 포트
server.port=9999

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 정적 리소스에 대해 캐시 사용 안 함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## OpenAI (OpenAI 비활성화로 인해 주석 처리)
# spring.ai.openai.api-key=dummy-key-for-spring-ai-startup
# spring.ai.openai.chat.options.model=gpt-4o-mini

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

## PGVector 테이블을 자동으로 생성하기 위한 설정(기본: false)
spring.ai.vectorstore.pgvector.initialize-schema=true

## PGVector 테이블 생성 위치 설정(기본)
# spring.ai.vectorstore.pgvector.schema-name=public
# spring.ai.vectorstore.pgvector.table-name=vector_store


#젬나기준
spring.ai.google.genai.embedding.model=text-embedding-004
spring.ai.google.genai.embedding.options.model=text-embedding-004

# PgVector 저장소 설정 (Google text-embedding-004 기준 768차원)
spring.ai.vectorstore.pgvector.dimensions=768


#####  PgVector 차원 수 및 OpenAI 자동 설정 비활성화
#spring.ai.vectorstore.pgvector.dimensions=1536
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration


## 벡터가 저장될 컬럼 설정: text-embedding-3-small 임베딩 모델을 사용할 경우
#spring.ai.openai.embedding.options.model=text-embedding-3-small
# spring.ai.vectorstore.pgvector.dimensions=1536
# spring.ai.vectorstore.pgvector.index-type=HNSW