server:
  port: 9999
  tomcat:
    deploy:
      enabled: false

spring:
  application:
    name: board1
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: totoro
    password: totoro123

mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:/mapper/*.xml