spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: "실제아이디@naver.com"
    password: "실제비밀번호"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com