-- 회원 테이블
CREATE TABLE users (
--               oracle 12c 이상 사용가능, id 번호 자동증가(시퀀스 역할)	
--    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 기본키
--    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 기본키

    id           NUMBER PRIMARY KEY,
    username     VARCHAR2(50) UNIQUE NOT NULL,  -- 로그인 ID
    password     VARCHAR2(200) NOT NULL,        -- 암호화된 비밀번호
    name         VARCHAR2(100),                 -- 이름
    email        VARCHAR2(100),                 -- 이메일
    role         VARCHAR2(20) DEFAULT 'USER',   -- 권한: USER / ADMIN
    reg_date     DATE DEFAULT SYSDATE           -- 가입일
);


create sequence users_seq
start with 1
increment by 1
nocache;

-- 시퀀스 삭제하고 싶으면 이렇게
DROP SEQUENCE users_seq;