spring.application.name=gradletest
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8090

# ⬇️ 스프링 부트가 원하는 DB 주소를 임시로 적어줘서 에러를 통과시킵니다.
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=scott
spring.datasource.password=tiger