spring.application.name=springai-vectordb

## 서버 포트
server.port=80

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 정적 리소스에 대해 캐시 사용 안 함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

## VectorStore
spring.ai.vectorstore.pgvector.initialize-schema=true     
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=chat_vector_store
spring.ai.vectorstore.pgvector.dimensions=1536











